<footer id="footer" class="midnight-blue">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                &copy; Gp Theme. All Rights Reserved.<br>
                 Site Web par Abdourahaman Soumare
                <?php
                $date= date("Y");
                print ($date);
                ?>
                <div class="credits">
                    <!--
                      All the links in the footer should remain intact.
                      You can delete the links only if you purchased the pro version.
                      Licensing information: https://bootstrapmade.com/license/
                      Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Gp
                    -->
                    Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                </div>
            </div>
            <div class="col-sm-6">
                <ul class="pull-right">
                    <li> <a href="index.php">Etat de la situation</a></li>
                    <li> <a href="plomb.php">Le plomb dans l'eau</a></li>
                    <li><a href="branchement.php">Mon branchement de service</a></li>
                    <li> <a href="actions.php">Les actions de la ville</a></li>
                    <li> <a href="solutions.php">Que faire ?</a></li>
                    <li> <a href="questions.php">Questions</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<!--/#footer-->

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="js/jquery.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery.prettyPhoto.js"></script>
<script src="js/jquery.isotope.min.js"></script>
<script src="js/wow.min.js"></script>
<script src="js/main.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
<script src="js/popup.js"></script>
<script src="js/horaire.js"></script>



</body>

</html>
